"""empty message

Revision ID: 576ac5ec9538
Revises: 
Create Date: 2026-04-19 20:23:41.042462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576ac5ec9538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_contacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('occupation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.VARCHAR(length=100), nullable=True))

    op.create_table('emergency_contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
