"""empty message

Revision ID: 967cc9b2f129
Revises: 
Create Date: 2026-04-19 10:24:33.721755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967cc9b2f129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('pronouns', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_monthly_rent', sa.Float(), nullable=False),
    sa.Column('monthly_rent_total', sa.Float(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('num_occupants', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('path', sa.String(length=4096), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('\n            (((unit_number / 100) BETWEEN 7 AND 35) AND ((unit_number % 100) BETWEEN 1 AND 12)) OR\n            (((unit_number / 100) = 36)                              AND ((unit_number % 100) BETWEEN 1 AND 6))\n            ', name='valid_unit_number'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leases')
    op.drop_table('emergency_contacts')
    op.drop_table('users')
    # ### end Alembic commands ###
