"""Add email verification to users

Revision ID: bb9e0752cb18
Revises: 576ac5ec9538
Create Date: 2026-08-27 00:41:00.445336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb9e0752cb18'
down_revision = '576ac5ec9538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment_unit_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('index_snapshot'))
        batch_op.drop_index(batch_op.f('index_unit_snapshot'))

    op.drop_table('apartment_unit_snapshots')
    op.drop_table('apartment_inventory_snapshots')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    op.create_table('apartment_inventory_snapshots',
    sa.Column('snapshot_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('apartment_inventory_snapshots_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apartment_inventory_snapshots_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('apartment_unit_snapshots',
    sa.Column('unit_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unit_num', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sq_footage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_available', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('snapshot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['apartment_inventory_snapshots.id'], name=op.f('apartment_unit_snapshots_snapshot_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('apartment_unit_snapshots_pkey'))
    )
    with op.batch_alter_table('apartment_unit_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('index_unit_snapshot'), ['unit_id', 'snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('index_snapshot'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###
