"""empty message

Revision ID: dda3bb77109e
Revises: 9a0e5c0f8d7c
Create Date: 2026-04-15 18:44:07.335575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda3bb77109e'
down_revision = '9a0e5c0f8d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_occupants', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_column('num_occupants')

    # ### end Alembic commands ###
